import Nav from './components/Nav'
import Footer from './components/Footer'
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Hydrate from './components/Hydrate'
import { Roboto, Lobster_Two, Satisfy } from 'next/font/google'


// Define the main font family

const roboto = Roboto({weight: ['400', '500', '700'], subsets: ['latin']})


export const metadata = {
  title: 'MonkeyBloom',
  description: 'Generated by OcPo Studio',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Fetch the user
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en" className={`${roboto.className}`}>
    
        <Hydrate>
       
          <Nav user={session?.user} expires={session?.expires as string} />
          {children}
          <Footer />
        
        </Hydrate>
       
    </html>
  )
}
